facade:
    host: "localhost"
    port: 8000

messages:
    - { host: "localhost", port: 8006 }
    - { host: "localhost", port: 8005 }
#     host: "localhost"
#     port: 8001

logging:
    - { host: "localhost", port: 8002 }
    - { host: "localhost", port: 8003 }
    - { host: "localhost", port: 8004 }
